  
trigger:
# - feature/*
- main

pool: 
 AITODO-Agent

# parameters:
# - name: tfsec_scanning
#   displayName: tfsec Required?
#   type: string
#   values:
#   - true
#   - false

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: terraforminstaller
      displayName: terraform Installer
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
    - template: Terraform-Template/Template-Init.yml
    - template: Terraform-Template/Template-Plan.yml  


  # - stage: Scanning
  #   pool: 
  #    AITODO-Agent
  #   displayName: Scanning
  #   jobs:
  #     - job: tfsec_scanning
  #       displayName: tfsec Scanning
  #       # condition: eq(parameters.tfsec_scanning, 'true')
  #       steps:
  #         - task: tfsec@1
  #           inputs:
  #             version: 'v1.26.0'
  #             dir: '$(System.DefaultWorkingDirectory)/todoapp_infra'
      # - job: tflint
      #   displayName: tflint
      #   steps:
          