jobs: 
 - job: terraformplan
   displayName: Terraform Plan      
   steps:        
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
         backendServiceArm: 'CodeNova_Connection'
         backendAzureRmResourceGroupName: 'rg'
         backendAzureRmStorageAccountName: 'rakshafurr1'
         backendAzureRmContainerName: 'pipeline'
         backendAzureRmKey: 'stages.tfstate' 
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'plan'
         workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
         environmentServiceNameAzureRM: 'CodeNova_Connection'